### ISSUE TITLE
Add More Credit Card Types

### ISSUE THREAD

**Issue by jrock2004** [adopted-ember-addons/ember-inputmask#134]
There are more card types that what is supported in current implementation. Can we add more card types

**Comment by RobbieTheWagner** [comment]
@jrock2004 I realize this is an old issue, but do you know what card types were missing that you needed?

**Comment by jrock2004** [comment]
I do not unfortunately

**Comment by RobbieTheWagner** [comment]
Closing this as wontfix for now.
